// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFqMtYkwtYjJil6m6K9clEGyjxyxo5qA',
    appId: '1:390637039939:web:61ec9caf4c845776773ff6',
    messagingSenderId: '390637039939',
    projectId: 'destiny-348ff',
    authDomain: 'destiny-348ff.firebaseapp.com',
    databaseURL: 'https://destiny-348ff-default-rtdb.firebaseio.com',
    storageBucket: 'destiny-348ff.appspot.com',
    measurementId: 'G-P02S25X3VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBC2XltZLoNdukMDyrxQ5pGpIi9uy_he8',
    appId: '1:390637039939:android:e070f5f0d1fcc08a773ff6',
    messagingSenderId: '390637039939',
    projectId: 'destiny-348ff',
    databaseURL: 'https://destiny-348ff-default-rtdb.firebaseio.com',
    storageBucket: 'destiny-348ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaFhdewug_unltiFa2E77pzF5nywvNQ4',
    appId: '1:390637039939:ios:9c774159b8bdc04f773ff6',
    messagingSenderId: '390637039939',
    projectId: 'destiny-348ff',
    databaseURL: 'https://destiny-348ff-default-rtdb.firebaseio.com',
    storageBucket: 'destiny-348ff.appspot.com',
    androidClientId: '390637039939-l21fadfblmtko4lj40e8ofp8tm80qqb6.apps.googleusercontent.com',
    iosClientId: '390637039939-o0kjv8gufal47tbg2hnjjle9319fjke8.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaFhdewug_unltiFa2E77pzF5nywvNQ4',
    appId: '1:390637039939:ios:9c774159b8bdc04f773ff6',
    messagingSenderId: '390637039939',
    projectId: 'destiny-348ff',
    databaseURL: 'https://destiny-348ff-default-rtdb.firebaseio.com',
    storageBucket: 'destiny-348ff.appspot.com',
    androidClientId: '390637039939-l21fadfblmtko4lj40e8ofp8tm80qqb6.apps.googleusercontent.com',
    iosClientId: '390637039939-o0kjv8gufal47tbg2hnjjle9319fjke8.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAFqMtYkwtYjJil6m6K9clEGyjxyxo5qA',
    appId: '1:390637039939:web:c4a36deeb2fe2098773ff6',
    messagingSenderId: '390637039939',
    projectId: 'destiny-348ff',
    authDomain: 'destiny-348ff.firebaseapp.com',
    databaseURL: 'https://destiny-348ff-default-rtdb.firebaseio.com',
    storageBucket: 'destiny-348ff.appspot.com',
    measurementId: 'G-5JVLR6VZT5',
  );
}
